### ISSUE TITLE
add sudo ufw allow 443

### ISSUE THREAD

**Issue by necocoa** [StirNetwork/server_lesson#12]
https://github.com/StirNetwork/server_lesson/blob/master/docs/0032_nginx_certbot_installation.md#%E8%A8%BC%E6%98%8E%E6%9B%B8%E3%82%92%E7%94%A8%E3%81%84%E3%81%9Fnginx-%E3%81%AE-https-%E8%A8%AD%E5%AE%9A
ファイヤーウォールのポート開放指示がなく、現状のままだとタイムアウトします。
項目の追加お願いします
```
sudo ufw allow 443
```

**Comment by kmn** [comment]
@necocoa PR,plz
