### ISSUE TITLE
https の強度を確認する の補足がほしい

### ISSUE THREAD

**Issue by necocoa** [StirNetwork/server_lesson#13]
https://github.com/StirNetwork/server_lesson/blob/master/docs/0032_nginx_certbot_installation.md#https-%E9%80%9A%E4%BF%A1%E3%82%92%E7%A2%BA%E8%AA%8D%E3%81%99%E3%82%8B

2. https://www.ssllabs.com/ssltest/ に移動して、https の強度を確認する
こちら、どういう結果だったら問題ないのか、など情報がほしいです。

例:
https://www.ssllabs.com/ssltest/analyze.html?d=necocoa.quelcode.k80s.net

**Comment by kmn** [comment]
@necocoa  A 以上を目指す。

Warning などあったら、修正する旨のPR 作成いただけますか？
